name: Ghost_Final_Build
on: [push]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install System Deps
        run: |
          sudo apt update
          sudo apt install -y git zip unzip python3-pip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev cmake libffi-dev libssl-dev build-essential
          pip install --user --upgrade "Cython<3.0" buildozer

      - name: Force Clean and Build
        run: |
          export PATH=$PATH:$HOME/.local/bin
          # Очистка перед сборкой, чтобы убить пустые 33МБ
          buildozer android clean
          yes | sdkmanager --licenses || true
          buildozer android debug
        env:
          BUILDOZER_ALLOW_ORG_GHOST: 1

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Ghost_Final_Core
          path: bin/*.apk
